// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AppInfo { app_id: string, version: number, date: number, name: string, submitter_uri: string | null, source_code_url: string | null, image: string, description: string, size: number, }