// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AppInfo { name: string, author_name: string, author_email: string | null, source_code_url: string | null, image: string | null, description: string, version: string | null, }