// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppInfo } from "./AppInfo";

export type ShopResponse = { type: "DownloadOkay", id: number, name: string, data: string, } | { type: "DownloadError", id: number, error: string, } | { type: "Update", app_infos: Array<AppInfo>, serial: number, };