// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppInfo } from "./AppInfo";

export type ShopResponse = { type: "DownloadOkay", app_id: string, name: string, data: string, } | { type: "DownloadError", app_id: string, error: string, } | { type: "Update", app_infos: Array<AppInfo>, serial: number, };