// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontendAppInfo } from "./FrontendAppInfo";

export interface UpdateResponse { app_infos: Array<FrontendAppInfo>, serial: number, }