// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppInfo } from "../../../bindings/AppInfo";

export interface UpdateResponse { app_infos: Array<AppInfo>, serial: bigint, }