// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AppInfo { name: string, author_name: string, author_email: string, source_code_url: string, image: string, description: string, xdc_blob_url: string, version: string, }