// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestType } from "./RequestType";

export interface StoreRequest { request_type: RequestType, data: string, }